CREATE TABLE reminder_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT NOT NULL UNIQUE,
    next_reminder_timestamp TIMESTAMP,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_retry_timestamp TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_reminder_transaction FOREIGN KEY (transaction_id) REFERENCES transaction(id) ON DELETE CASCADE
);

CREATE INDEX idx_reminder_next_timestamp ON reminder_schedule(next_reminder_timestamp) WHERE is_enabled = TRUE;
