spring:
  application:
    name: backend
  jpa:
    open-in-view: false
    properties:
      "[hibernate.format_sql]": true
  data:
    redis:
      timeout: 2s

server:
  port: ${SERVER_PORT:8080}

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui.html

app:
  security:
    user:
      name: ${APP_SECURITY_USER}
      password: ${APP_SECURITY_PASSWORD}
