import {
  Activity,
  Banknote,
  Bolt,
  Book,
  Car,
  ChevronRight,
  ChartBar,
  CreditCard,
  Dumbbell,
  Film,
  Filter,
  FileText,
  Gift,
  Home,
  Image as ImageIcon,
  Laptop,
  Landmark,
  PawPrint,
  Plane,
  Receipt,
  Repeat,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  TrendingDown,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  X,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  bolt: Bolt,
  heartbeat: Activity,
  film: Film,
  book: Book,
  wallet: Wallet,
  receipt: Receipt,
  'credit-card': CreditCard,
  'shopping-bag': ShoppingBag,
  plane: Plane,
  users: Users,
  sparkles: Sparkles,
  banknote: Banknote,
  shield: Shield,
  laptop: Laptop,
  gift: Gift,
  dumbbell: Dumbbell,
  'paw-print': PawPrint,
}

export const PAYMENT_METHOD_ICONS: Record<string, LucideIcon> = {
  CASH_ON_HAND: Banknote,
  BANK_ACCOUNT: Landmark,
  E_WALLET: Smartphone,
}

export const UI_ICONS: Record<string, LucideIcon> = {
  close: X,
  income: TrendingUp,
  expense: TrendingDown,
  note: FileText,
  recurring: Repeat,
  'chevron-right': ChevronRight,
  'chart-bar': ChartBar,
  filter: Filter,
  image: ImageIcon,
}
