import {
  Activity,
  AlertCircle,
  ArrowRight,
  Banknote,
  Bolt,
  Book,
  Camera,
  Car,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChartBar,
  CreditCard,
  Download,
  Dumbbell,
  ExternalLink,
  Film,
  Filter,
  FileText,
  Gift,
  Hand,
  Home,
  Image as ImageIcon,
  Info,
  Laptop,
  Landmark,
  PawPrint,
  Pencil,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Shield,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Wifi,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react'

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  home: Home,
  utensils: Utensils,
  car: Car,
  bolt: Bolt,
  heartbeat: Activity,
  film: Film,
  book: Book,
  wallet: Wallet,
  receipt: Receipt,
  'credit-card': CreditCard,
  'shopping-bag': ShoppingBag,
  plane: Plane,
  users: Users,
  sparkles: Sparkles,
  banknote: Banknote,
  shield: Shield,
  laptop: Laptop,
  gift: Gift,
  dumbbell: Dumbbell,
  'paw-print': PawPrint,
}

export const PAYMENT_METHOD_ICONS: Record<string, LucideIcon> = {
  CASH_ON_HAND: Banknote,
  BANK_ACCOUNT: Landmark,
  E_WALLET: Smartphone,
}

export const UI_ICONS: Record<string, LucideIcon> = {
  close: X,
  edit: Pencil,
  trash: Trash2,
  plus: Plus,
  search: Search,
  download: Download,
  camera: Camera,
  income: TrendingUp,
  expense: TrendingDown,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  note: FileText,
  image: ImageIcon,
  receipt: Receipt,
  wallet: Wallet,
  target: Target,
  hand: Hand,
  recurring: Repeat,
  refresh: RefreshCw,
  'external-link': ExternalLink,
  'arrow-right': ArrowRight,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chart-bar': ChartBar,
  'check-square': CheckSquare,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  filter: Filter,
  check: Check,
  info: Info,
  wifi: Wifi,
  'wifi-off': WifiOff,
}
