import {
  AlertCircle,
  ArrowRight,
  Banknote,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChartBar,
  Download,
  ExternalLink,
  Filter,
  FileText,
  Hand,
  Image as ImageIcon,
  Info,
  Landmark,
  Pencil,
  Plus,
  Receipt,
  RefreshCw,
  Repeat,
  Search,
  Smartphone,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Wallet,
  Wifi,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react'

export const PAYMENT_METHOD_ICONS: Record<string, LucideIcon> = {
  CASH_ON_HAND: Banknote,
  BANK_ACCOUNT: Landmark,
  E_WALLET: Smartphone,
}

export const UI_ICONS: Record<string, LucideIcon> = {
  close: X,
  edit: Pencil,
  trash: Trash2,
  plus: Plus,
  search: Search,
  download: Download,
  camera: Camera,
  income: TrendingUp,
  expense: TrendingDown,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  note: FileText,
  image: ImageIcon,
  receipt: Receipt,
  wallet: Wallet,
  target: Target,
  hand: Hand,
  recurring: Repeat,
  refresh: RefreshCw,
  'external-link': ExternalLink,
  'arrow-right': ArrowRight,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chart-bar': ChartBar,
  'check-square': CheckSquare,
  'check-circle': CheckCircle,
  'alert-circle': AlertCircle,
  filter: Filter,
  check: Check,
  info: Info,
  wifi: Wifi,
  'wifi-off': WifiOff,
}
